services:
  # PHP-FPM Service
  app:
    build: .
    container_name: vinko-app
    restart: always
    volumes:
      - .:/app
    environment:
      APP_URL: "https://baimo-tupipei.online"

  # Nginx Service (Internal Docker)
  web:
    image: nginx:alpine
    container_name: vinko-web
    restart: always
    ports:
      - "9000:80" # Port 9000 VPS ke Port 80 Nginx Docker
    volumes:
      - .:/app
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: vinko-db
    restart: always
    environment:
      POSTGRES_DB: vinko_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manchester
    ports:
      - "5435:5432"
    volumes:
      - vinko_db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: vinko-redis
    restart: always
    ports:
      - "6385:6379"

volumes:
  vinko_db_data: