services:
  app:
    build: .
    container_name: vinko-app
    restart: always
    ports:
      - "9000:8000" # Akses lewat IP:9000
    volumes:
      - .:/app
    environment:
      SERVER_NAME: ":8000"
      FRANKENPHP_CONFIG: "worker ./public/index.php"
      APP_URL: "https://baimo-tupipei.online"
      APP_ENV: production
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: vinko-db
    restart: always
    environment:
      POSTGRES_DB: vinko_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manchester
    ports:
      - "5435:5432"
    volumes:
      - vinko_db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: vinko-redis
    restart: always
    ports:
      - "6385:6379"

  horizon:
    build: .
    container_name: vinko-horizon
    restart: always
    volumes:
      - .:/app
    command: php artisan horizon
    depends_on:
      - db
      - redis

volumes:
  vinko_db_data: