server {
    listen 80;
    index index.php index.html;
    server_name _;
    root /app/public;

    # PENTING: Izinkan upload besar di sisi Nginx
    client_max_body_size 600M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass vinko-app:9000; # Merujuk ke nama service di docker-compose
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        # Timeout panjang untuk upload file besar
        fastcgi_read_timeout 600;
    }
}